import type { ServiceConfig, ServiceEntry } from '../../core/types/index.js';

export const GENERATED_SERVICES_DART_PATH = 'lib/flutter_config_manager_services.dart';

const HEADER = `// Generated by Flutter Config Manager. Do not edit manually.\n`;
const ACTIVE_SERVICES_PREFIX = '// Active services: ';

/** Build non-secret runtime constants that still require explicit use by app code. */
export function buildDartServiceConfig(
    services: ServiceEntry[],
    servicesConfig: ServiceConfig[],
): string | undefined {
    const configuredIds = new Set(servicesConfig.map(config => config.id));
    const activeServiceIds = Array.from(new Set(
        services.map(service => service.id).filter(id => configuredIds.has(id)),
    )).sort();
    const constants: Array<{ name: string; value: string }> = [];
    for (const service of services) {
        const config = servicesConfig.find(candidate => candidate.id === service.id);
        for (const constant of config?.dartConstants ?? []) {
            const value = service.values?.[constant.valueField]?.trim();
            if (value) {constants.push({ name: constant.name, value });}
        }
    }
    if (activeServiceIds.length === 0) {return undefined;}

    const declarations = constants
        .sort((left, right) => left.name.localeCompare(right.name))
        .map(({ name, value }) => `  static const String ${name} = r'${value}';`)
        .join('\n');
    const body = declarations ? `${declarations}\n` : '';
    return `${HEADER}${ACTIVE_SERVICES_PREFIX}${activeServiceIds.join(', ')}\n\nclass FlutterConfigManagerServices {\n  FlutterConfigManagerServices._();\n${body}}\n`;
}

/** Restore generated values so configured services survive extension reloads. */
export function extractDartServiceConfig(
    content: string | undefined,
    servicesConfig: ServiceConfig[],
): ServiceEntry[] {
    if (!content?.startsWith(HEADER)) {return [];}
    const knownIds = new Set(servicesConfig.map(config => config.id));
    const activeIds = new Set(
        content.match(new RegExp(`^${ACTIVE_SERVICES_PREFIX}(.+)$`, 'm'))?.[1]
            .split(',')
            .map(value => value.trim())
            .filter(value => knownIds.has(value)) ?? [],
    );
    const valuesByName = new Map<string, string>();
    for (const match of content.matchAll(/static const String\s+(\w+)\s*=\s*r'([^']*)';/g)) {
        valuesByName.set(match[1], match[2]);
    }

    return servicesConfig.flatMap(config => {
        const values: Record<string, string> = {};
        for (const constant of config.dartConstants ?? []) {
            const value = valuesByName.get(constant.name);
            if (value !== undefined) {values[constant.valueField] = value;}
        }
        return activeIds.has(config.id) || Object.keys(values).length > 0
            ? [{ id: config.id, values }]
            : [];
    });
}
